### ISSUE TITLE
Add basic configuration and info files

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-serhii73#4]
* [x] `README.md`, stating your project title, styled with Markdown
* [x] `LICENSE` file. Find template for it in plain text or Markdown format. You may use MIT licence for simplicity
* [x] `.gitattributes`. Find some template for your repo on github
* [x] `.gitignore`. Find typical template for your language (Python, Vim, Linux etc.) @ gitignore.io

You'll need to push a new branch (e.g. `features/3-initial-config`) with atomic commits and create a PR referencing this issue.

**Comment by serhii73** [comment]
@webknjaz please review https://github.com/kpi-web-guild/django-girls-blog-serhii73/tree/features/initial-config

**Comment by webknjaz** [comment]
It is impossible to "review" a branch, only PR. Also you are not supposed to push to master.

**Comment by webknjaz** [comment]
Oh, you don't have master. So create it, create an empty initial commit there and then rebase your branch on top of it and create a new PR

**Comment by serhii73** [comment]
I'm confused. @webknjaz can you just delete all my branches? I need a clean repository again.

**Comment by serhii73** [comment]
https://help.github.com/articles/setting-the-default-branch/ - And I don't have a settings button.

**Comment by webknjaz** [comment]
I've switched default to `master` in settings

**Comment by serhii73** [comment]
@webknjaz Thank you. https://github.com/kpi-web-guild/django-girls-blog-serhii73/pull/17 - I am create PR for this issue. 
P.S. I right understand, in this project I don't need `git commit` like `Resolves #4`, right?

**Comment by webknjaz** [comment]
You may use keywords. You do not need a separate PR

**Comment by serhii73** [comment]
@webknjaz https://github.com/kpi-web-guild/django-girls-blog-serhii73/pull/18
