### ISSUE TITLE
Configure integration of Heroku deployment with GitHub

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-serhii73#9]
* [x] Accept invitation to [this organization](https://github.com/kpi-web-guild)
 * optionally make your membership public, so that there will be hat logo displayed on your profile page ^^
* [x] Choose [this repo](https://github.com/kpi-web-guild/django-girls-blog-serhii73) in `Heroku Dashboard` on `Deploy` page
* [x] Make [`master` branch](https://github.com/kpi-web-guild/django-girls-blog-serhii73/tree/master) be deployed on update once the tests pass

**Comment by serhii73** [comment]
@webknjaz I will deployment only on Heroku? Or pythonanywhere too?

**Comment by webknjaz** [comment]
This task is about Heroku. You can do other platform deployments later separately.

**Comment by serhii73** [comment]
https://tutorial-extensions.djangogirls.org/en/heroku/

**Comment by serhii73** [comment]
![screenshot from 2018-07-13 13-46-08](https://user-images.githubusercontent.com/24910277/42687946-26484344-86a3-11e8-9d6f-6e01d9b139dc.png)
@webknjaz now I can to close this issue? Right?

**Comment by webknjaz** [comment]
Well, you need to try to deploy this app there manually using git+ssh way of doing that.

**Comment by serhii73** [comment]
@webknjaz https://serhii73-django-girls.herokuapp.com/ , now I can to close the issue?
